# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_auth', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
