# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('w_post', '0003_post_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('my_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique_for_date='publish'),
        ),
    ]
