# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_post', '0005_jianshupost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jianshupost',
            name='keyword',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
