# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('w_auth', '0002_auto_20170722_1907'),
        ('w_post', '0004_auto_20170723_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_user', models.IntegerField()),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='w_auth.User')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='w_comment.Comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='w_post.Post')),
            ],
        ),
    ]
